In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts

<bound method IndexOpsMixin.value_counts of 0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Category, Length: 5572, dtype: str>

In [5]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [6]:
df.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [8]:
len(x_train)

4457

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_cv=v.fit_transform(x_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59211 stored elements and shape (4457, 7678)>

In [10]:
x_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(2, 7678))

In [11]:
x_train_cv.shape

(4457, 7678)

In [13]:
v.get_feature_names_out()[10:30]

array(['02085076972', '021', '03', '04', '0430', '05', '050703', '0578',
       '06', '07', '07008009200', '07046744435', '07090201529',
       '07090298926', '07099833605', '07123456789', '0721072',
       '07732584351', '07734396839', '07742676969'], dtype=object)

In [14]:
v.vocabulary_

{'sms': 6219,
 'services': 5993,
 'for': 2932,
 'your': 7647,
 'inclusive': 3649,
 'text': 6738,
 'credits': 2074,
 'pls': 5217,
 'goto': 3205,
 'www': 7580,
 'comuk': 1953,
 'net': 4713,
 'login': 4157,
 '3qxj9': 459,
 'unsubscribe': 7128,
 'with': 7484,
 'stop': 6449,
 'no': 4763,
 'extra': 2729,
 'charge': 1735,
 'help': 3394,
 '08702840625': 81,
 '220': 356,
 'cm2': 1872,
 '9ae': 728,
 'hey': 3417,
 'you': 7642,
 'around': 1063,
 've': 7206,
 'got': 3201,
 'enough': 2607,
 'half': 3301,
 'the': 6764,
 'ten': 6716,
 'owe': 4992,
 'message': 4428,
 'responce': 5704,
 'what': 7415,
 'happend': 3321,
 'then': 6774,
 'come': 1912,
 'wenever': 7400,
 'lik': 4089,
 'to': 6878,
 'and': 953,
 'also': 916,
 'tel': 6702,
 'vikky': 7234,
 'by': 1589,
 'getting': 3122,
 'free': 2975,
 'time': 6847,
 'thanks': 6755,
 'subscription': 6518,
 'ringtone': 5751,
 'uk': 7068,
 'mobile': 4513,
 'will': 7456,
 'be': 1267,
 'charged': 1736,
 'month': 4547,
 'please': 5210,
 'confirm': 1965,
 'replying': 5678,
 'yes': 7626,
 'or': 4935,
 'if': 3596,
 'reply': 5677,
 'not': 4796,
 'hi': 3421,
 'its': 3758,
 'me': 4376,
 'are': 1042,
 'probably': 5392,
 'having': 3354,
 'too': 6918,
 'much': 4603,
 'fun': 3034,
 'get': 3115,
 'this': 6798,
 'but': 1577,
 'thought': 6809,
 'id': 3584,
 'txt': 7041,
 'cos': 2025,
 'im': 3613,
 'bored': 1438,
 'james': 3776,
 'has': 3336,
 'been': 1288,
 'farting': 2771,
 'at': 1112,
 'all': 902,
 'night': 4744,
 'aiyah': 879,
 'sorry': 6287,
 'lor': 4183,
 'watch': 7343,
 'tv': 7029,
 'until': 7131,
 'forgot': 2944,
 'check': 1756,
 'my': 4632,
 'phone': 5147,
 'thats': 6763,
 'cool': 2010,
 'am': 925,
 'gentleman': 3106,
 'treat': 6977,
 'dignity': 2327,
 'respect': 5702,
 'alright': 914,
 'll': 4136,
 'head': 3360,
 'out': 4968,
 'in': 3640,
 'few': 2810,
 'minutes': 4472,
 'where': 7425,
 'meet': 4395,
 'dear': 2201,
 'voucher': 7270,
 'holder': 3461,
 'claim': 1826,
 'weeks': 7384,
 'offer': 4862,
 'pc': 5088,
 'go': 3160,
 'http': 3534,
 'tlp': 6867,
 'co': 1878,
 'expressoffer': 2726,
 'ts': 7006,
 'cs': 2095,
 'apply': 1018,
 'texts': 6748,
 '80062': 627,
 'take': 6645,
 'mokka': 4531,
 'players': 5206,
 'only': 4909,
 'how': 3519,
 'ages': 859,
 'abj': 750,
 'had': 3290,
 'money': 4539,
 'issue': 3749,
 'weigh': 7385,
 'down': 2434,
 'can': 1629,
 'breathe': 1497,
 'easier': 2513,
 'now': 4809,
 'make': 4299,
 'sure': 6581,
 'dont': 2419,
 'regret': 5629,
 'it': 3751,
 'call': 1605,
 'later': 4006,
 'gonna': 3181,
 'able': 751,
 'late': 4004,
 'notice': 4802,
 'home': 3469,
 'anyway': 995,
 'plans': 5200,
 'see': 5944,
 'an': 948,
 'hour': 3512,
 'surly': 6586,
 'ill': 3609,
 'give': 3141,
 'while': 7432,
 'coming': 1918,
 'review': 5731,
 'there': 6778,
 'we': 7361,
 'have': 3349,
 'moved': 4573,
 'in2': 3641,
 'our': 4966,
 'pub': 5446,
 'would': 7550,
 'great': 3232,
 'cud': 2110,
 'up': 7133,
 'yeah': 7614,
 'try': 7003,
 'scrounge': 5919,
 'something': 6262,
 'they': 6784,
 'replied': 5676,
 'mail': 4291,
 'going': 3173,
 'management': 4313,
 'office': 4866,
 'plus': 5222,
 'bank': 1213,
 'on': 4900,
 'wednesday': 7376,
 'left': 4044,
 'already': 913,
 'orchard': 4941,
 'came': 1624,
 'last': 4001,
 'min': 4453,
 'think': 6790,
 'wun': 7579,
 'signing': 6118,
 'tmr': 6872,
 'hee': 3382,
 'yo': 7637,
 'guys': 3281,
 'ever': 2664,
 'figure': 2825,
 'need': 4695,
 'alcohol': 890,
 'jay': 3789,
 'trying': 7005,
 'safely': 5837,
 'spend': 6337,
 'weed': 7378,
 'winner': 7467,
 'as': 1080,
 'valued': 7194,
 'network': 4718,
 'customer': 2133,
 'selected': 5955,
 'receivea': 5586,
 '900': 713,
 'prize': 5387,
 'reward': 5733,
 '09061701461': 191,
 'code': 1888,
 'kl341': 3934,
 'valid': 7190,
 '12': 275,
 'hours': 3514,
 'smoking': 6217,
 'people': 5105,
 'use': 7168,
 'wylie': 7581,
 'smokes': 6215,
 'justify': 3864,
 'ruining': 5812,
 'shit': 6059,
 'oh': 4876,
 'icic': 3579,
 'den': 2250,
 'other': 4959,
 'day': 2189,
 'short': 6076,
 'cute': 2138,
 'good': 3183,
 'person': 5122,
 'prove': 5431,
 'gud': 3264,
 'mrng': 4582,
 'so': 6238,
 'deus': 2288,
 'ex': 2686,
 'congrats': 1971,
 'kano': 3880,
 'whr': 7442,
 'maga': 4280,
 'delhi': 2241,
 'chennai': 1770,
 'still': 6436,
 'silent': 6121,
 'just': 3863,
 'normal': 4790,
 'here': 3407,
 'inside': 3688,
 'filling': 2832,
 'forms': 2952,
 'don': 2415,
 'know': 3941,
 'when': 7421,
 'leave': 4038,
 'camera': 1625,
 'phones': 5151,
 'linerental': 4105,
 'from': 3013,
 '49': 502,
 '750': 609,
 'cross': 2085,
 'ntwk': 4817,
 'mins': 4468,
 'price': 5369,
 'bundle': 1559,
 'deals': 2200,
 'avble': 1152,
 '08001950382': 54,
 'call2optout': 1607,
 'mf': 4437,
 'hoping': 3493,
 'away': 1166,
 'langport': 3987,
 'town': 6947,
 'tonight': 6913,
 'dun': 2491,
 'say': 5885,
 'early': 2508,
 'hor': 3494,
 'urgent': 7155,
 'won': 7511,
 '000': 1,
 'bonus': 1427,
 'caller': 1612,
 '02': 7,
 '06': 18,
 '03': 12,
 'is': 3740,
 '2nd': 398,
 'attempt': 1121,
 'reach': 5551,
 '09066362220': 226,
 'asap': 1082,
 'box97n7qp': 1470,
 '150ppm': 302,
 'que': 5481,
 'pases': 5058,
 'un': 7078,
 'buen': 1547,
 'tiempo': 6837,
 'like': 4090,
 'that': 6762,
 'loan': 4144,
 'any': 984,
 'purpose': 5464,
 '500': 526,
 '75': 608,
 'homeowners': 3470,
 'tenants': 6717,
 'welcome': 7393,
 'previously': 5367,
 'refused': 5620,
 '0800': 48,
 '1956669': 321,
 'back': 1188,
 'opening': 4921,
 'mca': 4372,
 'yup': 7663,
 'her': 3406,
 'fren': 2986,
 'meeting': 4397,
 '730': 606,
 'way': 7356,
 '07801543489': 36,
 'guaranteed': 3262,
 'latests': 4008,
 'nokia': 4772,
 '40gb': 474,
 'ipod': 3731,
 'mp3': 4579,
 'player': 5205,
 'word': 7527,
 'collect': 1898,
 '83355': 655,
 'tc': 6681,
 'llc': 4137,
 'ny': 4834,
 'usa': 7165,
 '150p': 298,
 'mt': 4593,
 'msgrcvd18': 4589,
 'xy': 7601,
 'lunch': 4238,
 'sez': 6010,
 'hows': 3523,
 'de': 2195,
 'arab': 1038,
 'boy': 1471,
 'hope': 3486,
 'love': 4205,
 'evry1': 2685,
 'ya': 7602,
 'eshxxxxxxxxxxx': 2642,
 'lol': 4163,
 'friend': 2997,
 'dog': 2397,
 'each': 2503,
 'moment': 4534,
 'own': 4995,
 'value': 7193,
 'morning': 4558,
 'brings': 1510,
 'afternoon': 848,
 'faith': 2751,
 'evening': 2660,
 'luv': 4241,
 'rest': 5710,
 'wish': 7476,
 'find': 2844,
 'them': 6771,
 'today': 6885,
 'unbelievable': 7080,
 'faglord': 2744,
 '11mths': 273,
 'update': 7138,
 'oranges': 4940,
 'latest': 4007,
 'colour': 1903,
 'mobiles': 4514,
 'unlimited': 7119,
 'weekend': 7381,
 'calls': 1619,
 'upd8': 7136,
 'freefone': 2979,
 '08000839402': 51,
 '2stoptxt': 408,
 '8007': 628,
 '1st': 331,
 'week': 7379,
 'no1': 4764,
 'tone': 6906,
 'ur': 7151,
 'mob': 4512,
 'every': 2665,
 'txting': 7047,
 'tell': 6707,
 'mates': 4351,
 'getzed': 3123,
 'pobox': 5229,
 '36504': 443,
 'w4': 7283,
 '5wq': 558,
 'norm': 4788,
 '16': 310,
 'lt': 4228,
 'gt': 3259,
 'of': 4858,
 'pple': 5311,
 'marry': 4337,
 'their': 6768,
 'lovers': 4212,
 'becz': 1281,
 'hav': 3346,
 'undrstndng': 7098,
 'dat': 2179,
 'avoids': 1160,
 'problems': 5395,
 'sent': 5979,
 'dis': 2349,
 'wil': 7454,
 'news': 4730,
 'friday': 2994,
 'tomorrow': 6904,
 'best': 1324,
 'life': 4078,
 'break': 1491,
 'chain': 1718,
 'suffer': 6531,
 'send': 5969,
 'frnds': 3007,
 'whn': 7435,
 'read': 5555,
 'excellent': 2691,
 'ready': 5558,
 'moan': 4511,
 'scream': 5914,
 'ecstasy': 2529,
 'boytoy': 1476,
 'goes': 3168,
 'walking': 7308,
 'did': 2308,
 'police': 5251,
 'abstract': 758,
 'about': 753,
 'wake': 7301,
 'miss': 4481,
 'babe': 1180,
 'dude': 2484,
 'longer': 4169,
 'pisces': 5182,
 'aquarius': 1036,
 'smile': 6209,
 'two': 7039,
 'crucial': 2088,
 'things': 6789,
 'sometimes': 6264,
 'makes': 4300,
 'us': 7164,
 'forget': 2939,
 'someone': 6256,
 'noon': 4781,
 'whenever': 7422,
 'show': 6089,
 'fuck': 3022,
 'jus': 3862,
 'reached': 5552,
 'bathe': 1244,
 'first': 2862,
 'sis': 6142,
 'using': 7175,
 'she': 6036,
 'finishes': 2852,
 'he': 3359,
 'lemme': 4051,
 're': 5550,
 'audrey': 1134,
 'status': 6415,
 'right': 5743,
 'well': 7395,
 'fine': 2846,
 'bbd': 1253,
 'pooja': 5263,
 'full': 3031,
 'pimples': 5178,
 'even': 2659,
 'become': 1278,
 'quite': 5492,
 'black': 1375,
 'rite': 5759,
 'cold': 1894,
 'wearing': 7366,
 'sweatter': 6608,
 'ttyl': 7014,
 'let': 4062,
 'before': 1294,
 'kicks': 3912,
 'off': 4860,
 'bit': 1367,
 'weird': 7389,
 'do': 2384,
 'supposed': 6577,
 'happening': 3324,
 'idea': 3585,
 'mean': 4379,
 'was': 7335,
 'working': 7533,
 'ok': 4881,
 'din': 2331,
 'msg': 4585,
 'plz': 5224,
 'note': 4797,
 'anyone': 988,
 'calling': 1617,
 'amp': 941,
 'asks': 1094,
 'type': 7054,
 'disconnect': 2357,
 'coz': 2053,
 'iz': 3766,
 'terrorist': 6729,
 'sim': 6125,
 'card': 1649,
 'itz': 3762,
 'confirmd': 1966,
 'motorola': 4567,
 'verified': 7213,
 'cnn': 1876,
 'ibn': 3574,
 'new': 4725,
 'semester': 5965,
 'very': 7218,
 'made': 4275,
 'greatness': 3235,
 'finish': 2849,
 'wanna': 7320,
 'vewy': 7220,
 'lubly': 4231,
 'xxx': 7595,
 'surely': 6582,
 'result': 5717,
 'garden': 3071,
 'summer': 6550,
 'selection': 5956,
 'bulbs': 1555,
 'seeds': 5945,
 'worth': 7545,
 '33': 438,
 '50': 525,
 'scotsman': 5909,
 'saturday': 5878,
 'go2': 3161,
 'notxt': 4805,
 'senthil': 5981,
 'hsbc': 3532,
 'ask': 1089,
 'next': 4734,
 'sat': 5871,
 'contact': 1986,
 'todays': 6886,
 'draw': 2446,
 'shows': 6095,
 '800': 625,
 '09050003091': 164,
 'land': 3980,
 'line': 4102,
 'c52': 1592,
 '12hrs': 281,
 'change': 1725,
 'suntec': 6564,
 'wat': 7342,
 'car': 1648,
 'sleep': 6173,
 'really': 5568,
 'broke': 1518,
 'amount': 940,
 'small': 6198,
 'girls': 3138,
 'always': 923,
 'safe': 5836,
 'selfish': 5959,
 'pa': 5003,
 'thank': 6754,
 'awarded': 1165,
 'city': 1824,
 'could': 2035,
 'win': 7459,
 '200': 341,
 'shopping': 6073,
 'spree': 6370,
 'wk': 7492,
 'store': 6457,
 '88039': 690,
 'skilgme': 6159,
 'tscs087147403231winawk': 7010,
 'age16': 855,
 '50perwksub': 532,
 'beerage': 1291,
 'pick': 5161,
 'rayan': 5541,
 'macleran': 4269,
 'award': 1164,
 '1000': 254,
 'cashto': 1676,
 '08000407165': 49,
 '18': 315,
 'getstop': 3120,
 '88222': 693,
 'php': 5156,
 'rg21': 5735,
 '4jx': 512,
 'pain': 5014,
 'another': 970,
 'spent': 6339,
 'casualty': 1680,
 'means': 4383,
 'haven': 3350,
 'done': 2417,
 'stuff42moro': 6498,
 'includes': 3647,
 'sheets': 6038,
 'maybe': 4370,
 'yck': 7613,
 'finn': 2855,
 'valentine': 7188,
 'game': 3062,
 'friends': 2998,
 'answers': 977,
 'same': 5853,
 'loves': 4213,
 'ques': 5484,
 'which': 7431,
 'suits': 6545,
 'celebrate': 1702,
 'family': 2761,
 'greetings': 3240,
 'consider': 1980,
 'yourself': 7652,
 'excused': 2697,
 'place': 5190,
 'want': 7322,
 'da': 2148,
 'bathroom': 1246,
 'sup': 6565,
 'amazing': 927,
 'quote': 5497,
 'difficult': 2322,
 'decide': 2209,
 'whats': 7417,
 'wrong': 7567,
 'lie': 4076,
 'truth': 7002,
 'tear': 6692,
 'noe': 4767,
 'leh': 4049,
 'advance': 825,
 'happy': 3328,
 'pongal': 5260,
 'fair': 2750,
 'anything': 993,
 'ugh': 7062,
 'hopefully': 3488,
 'asus': 1110,
 'ppl': 5310,
 'randomly': 5527,
 'reformat': 5617,
 'grinder': 3242,
 'catching': 1684,
 'watching': 7346,
 'wan': 7317,
 'single': 6136,
 'fighting': 2822,
 'said': 5840,
 'didnt': 2311,
 'added': 804,
 'list': 4118,
 'fullonsms': 3032,
 'com': 1906,
 'more': 4554,
 'visit': 7249,
 'both': 1446,
 'logo': 4158,
 'lover': 4210,
 'names': 4656,
 'joined': 3828,
 'heart': 3374,
 'name1': 4653,
 'name2': 4654,
 'mobno': 4518,
 'eg': 2546,
 'adam': 801,
 'eve': 2657,
 '07123456789': 25,
 '87077': 683,
 'yahoo': 7604,
 'pobox36504w45wq': 5234,
 'txtno': 7048,
 'ads': 822,
 'uncle': 7083,
 'abbey': 742,
 'year': 7615,
 'abiola': 749,
 'responding': 5706,
 'room': 5780,
 'went': 7401,
 'diwali': 2375,
 'one': 4904,
 'called': 1611,
 'why': 7443,
 'feel': 2796,
 'died': 2313,
 'understand': 7093,
 'wine': 7464,
 'slurp': 6196,
 'most': 4561,
 'wi': 7444,
 'nz': 4839,
 'unsold': 7125,
 'wait': 7297,
 'rain': 5510,
 'thangam': 6753,
 'mistake': 4490,
 'virtual': 7246,
 'hug': 3539,
 'sipix': 6139,
 'digital': 2326,
 '09061221061': 189,
 'landline': 3982,
 'delivery': 2246,
 'within': 7487,
 '28days': 374,
 'box177': 1458,
 'm221bp': 4250,
 '2yr': 416,
 'warranty': 7333,
 '99': 726,
 'mum': 4611,
 'shun': 6102,
 'bian': 1342,
 'glass': 3148,
 'exhibition': 2705,
 'evry': 2684,
 'emotion': 2581,
 'dsn': 2480,
 'words': 7528,
 'prayrs': 5334,
 'world': 7536,
 'wit': 7483,
 'othrwise': 4963,
 'drop': 2466,
 'stay': 6416,
 'keep': 3890,
 'smiling': 6212,
 'jon': 3837,
 'pete': 5132,
 'ive': 3764,
 'bin': 1357,
 'spain': 6313,
 'recently': 5590,
 'sum': 6547,
 'dinero': 2334,
 'bill': 1350,
 'rents': 5667,
 'mayb': 4369,
 'interested': 3702,
 '000pes': 2,
 '48': 500,
 'tb': 6680,
 'spatula': 6320,
 'hands': 3312,
 'lost': 4190,
 'pounds': 5303,
 'since': 6131,
 'doc': 2387,
 'woot': 7523,
 'stuffing': 6500,
 'face': 2737,
 'lets': 4063,
 'monday': 4538,
 'per': 5106,
 'convenience': 1998,
 'shame': 6023,
 'takes': 6647,
 'runs': 5819,
 'blame': 1380,
 'long': 4168,
 'blimey': 1391,
 'exercise': 2701,
 'kinda': 3922,
 'remember': 5647,
 'wot': 7547,
 'hmm': 3451,
 'schedule': 5899,
 'actually': 799,
 'decided': 2210,
 'hungry': 3549,
 'yet': 7629,
 'hip': 3434,
 'hop': 3485,
 'open': 4918,
 'haha': 3293,
 'thinking': 6793,
 'jazz': 3792,
 'zoom': 7672,
 'cine': 1821,
 'kb': 3887,
 'lesson': 4060,
 'serious': 5988,
 'base': 1233,
 'saw': 5884,
 'battery': 1249,
 'low': 4218,
 'bhaji': 1340,
 'told': 6895,
 'kallis': 3875,
 'cricketer': 2080,
 'after': 846,
 'sachin': 5830,
 'tough': 6943,
 'upto': 7149,
 '12mths': 282,
 '2price': 404,
 '100txt': 258,
 'mth': 4595,
 'tooth': 6924,
 'mobileupd8': 4517,
 '2optout': 402,
 'd3wv': 2147,
 'sleeping': 6175,
 'might': 4445,
 'gr8': 3211,
 'rock': 5766,
 'wen': 7398,
 'studying': 6495,
 'sch': 5898,
 'oz': 5002,
 'kind': 3921,
 'shitload': 6061,
 'b4': 1175,
 'thursday': 6830,
 'double': 2429,
 'orange': 4939,
 'bluetooth': 1409,
 'offers': 4865,
 'lf56': 4067,
 'job': 3819,
 'prospects': 5429,
 'missing': 4485,
 'being': 1306,
 'lazy': 4023,
 'bleak': 1385,
 'hmmm': 3452,
 'filled': 2831,
 'acknowledgement': 784,
 'astoundingly': 1107,
 'tactless': 6638,
 'generally': 3101,
 'faggy': 2743,
 'demand': 2249,
 'blood': 1401,
 'oath': 4843,
 'fo': 2911,
 'olol': 4895,
 'printed': 5377,
 'forum': 2955,
 'post': 5290,
 'guy': 3280,
 'exact': 2687,
 'prob': 5391,
 'fixed': 2871,
 'gpu': 3210,
 'replacement': 5674,
 'ignore': 3601,
 'doing': 2406,
 'admin': 812,
 'building': 1553,
 'slightly': 6185,
 'earlier': 2506,
 'reaching': 5553,
 'once': 4902,
 'grinule': 3244,
 'greet': 3238,
 'speak': 6321,
 'shoppin': 6072,
 'area': 1043,
 'name': 4652,
 'hotel': 3507,
 'xmas': 7589,
 'radio': 5503,
 'times': 6848,
 'driving': 2463,
 'ic': 3576,
 'lotta': 4196,
 'childporn': 1786,
 'cars': 1670,
 'common': 1924,
 'hearin': 3372,
 'different': 2321,
 'evng': 2679,
 'omg': 4898,
 'joanna': 3818,
 'freaking': 2972,
 'looked': 4174,
 'thru': 6824,
 'photos': 5154,
 'asking': 1093,
 'stuff': 6497,
 'myspace': 4637,
 'logged': 4155,
 'fr': 2965,
 'wif': 7449,
 'donno': 2418,
 'scorable': 5903,
 'sake': 5841,
 'tallahassee': 6659,
 'him': 3430,
 'thing': 6788,
 'get4an18th': 3116,
 'spoke': 6357,
 'maneesha': 4318,
 'were': 7404,
 'satisfied': 5875,
 'experience': 2714,
 'toll': 6898,
 'granite': 3223,
 'issues': 3750,
 'strong': 6480,
 'buy': 1582,
 'explosive': 2723,
 'members': 4411,
 'over': 4983,
 '300': 419,
 'nasdaq': 4665,
 'symbol': 6624,
 'cdgt': 1697,
 '00': 0,
 'germany': 3114,
 'pence': 5100,
 'minute': 4471,
 'via': 7221,
 'access': 769,
 'number': 4820,
 '0844': 65,
 '861': 676,
 '85': 667,
 'prepayment': 5349,
 'direct': 2342,
 'nah': 4646,
 'man': 4309,
 'meant': 4384,
 'crammed': 2059,
 '0a': 250,
 'networks': 4720,
 'allow': 906,
 'companies': 1928,
 'responsible': 5709,
 'suppliers': 6571,
 'shop': 6071,
 'guarantee': 3261,
 'sell': 5961,
 'lifting': 4085,
 'congratulations': 1973,
 'vip': 7241,
 'row': 5792,
 'tickets': 6835,
 'blu': 1407,
 'concert': 1958,
 'november': 4808,
 'gift': 3128,
 '09061104276': 185,
 'smsco': 6220,
 'cost': 2027,
 '75max': 611,
 'clothes': 1861,
 'jewelry': 3809,
 ...}

In [16]:
x_train_cp=x_train_cv.toarray()
x_train_cp[:4][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7678,))

In [17]:
np.where(x_train_cp[0]!=0)

(array([  81,  356,  459,  728, 1735, 1872, 1953, 2074, 2729, 2932, 3205,
        3394, 3649, 4157, 4713, 4763, 5217, 5993, 6219, 6449, 6738, 7128,
        7484, 7580, 7647]),)

In [18]:
x_train[:4]

5497    SMS SERVICES. for your inclusive text credits,...
3283    Hey you around? I've got enough for a half + t...
2387               No message..no responce..what happend?
5148    K..then come wenever u lik to come and also te...
Name: Message, dtype: str

In [19]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [20]:
x_test_cv=v.transform(x_test)

In [22]:
from sklearn.metrics import classification_report
y_pred=model.predict(x_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       970
           1       0.96      0.90      0.93       145

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

In [24]:
emails=[
  'Hey mohan, can we get together to watch football game tomorrow',
  'Upto 20% discount on parking, exclusive offer just for you . Dont miss the reward!'
]
emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1])