In [102]:
import pandas as pd
df=pd.read_csv("weight-height.csv")
df.head(20)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Gender  10000 non-null  object
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB

In [103]:
df.describe()

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [104]:
q1=df.Weight.quantile(0.25)
q1

np.float64(135.8180513055015)

In [105]:
q3=df.Weight.quantile(0.75)
q3

np.float64(187.16952486868348)

In [106]:
iqr=q3-q1
upperLimit=q3+1.5*iqr

upperLimit

np.float64(264.19673521345646)

In [107]:
lowerLimit=q1-1.5*iqr
lowerLimit

np.float64(58.79084096072856)

In [108]:
df[(df.Weight<lowerLimit) | (df.Weight>upperLimit) ]

     Gender     Height      Weight
2014   Male  78.998742  269.989699