In [46]:
import pandas as pd
df=pd.read_csv("weight-height.csv")
df.head(20)

   Gender     Height      Weight
0    Male  73.847017  241.893563
1    Male  68.781904  162.310473
2    Male  74.110105  212.740856
3    Male  71.730978  220.042470
4    Male  69.881796  206.349801
5    Male  67.253016  152.212156
6    Male  68.785081  183.927889
7    Male  68.348516  167.971110
8    Male  67.018950  175.929440
9    Male  63.456494  156.399676
10   Male  71.195382  186.604926
11   Male  71.640805  213.741169
12   Male  64.766329  167.127461
13   Male  69.283070  189.446181
14   Male  69.243732  186.434168
15   Male  67.645620  172.186930
16   Male  72.418317  196.028506
17   Male  63.974326  172.883470
18   Male  69.640060  185.983958
19   Male  67.936005  182.426648

In [47]:
df.describe()

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [48]:
q1=df.Height.quantile(0.25)
q1

np.float64(63.505620481218955)

In [49]:
q3=df.Height.quantile(0.75)
q3

np.float64(69.1742617268347)

In [50]:
iqr=q3-q1
upperLimit=q3+1.5*iqr

upperLimit

np.float64(77.67722359525831)

In [51]:
lowerLimit=q1-1.5*iqr
lowerLimit

np.float64(55.00265861279534)

In [ ]:
df((df.Height<lowerLimit) | (df.Height>upperLimit) )

TypeError: 'DataFrame' object is not callable